name: ServerAccount
version: ${project.version}
main: dev.hjjang.serveraccount.ServerAccountPlugin
api-version: '1.21'
description: Server treasury account with admin commands and transaction logging
author: hjjang
depend: [Vault]
softdepend: [Essentials]

commands:
  serveraccount:
    description: Server account management commands
    usage: /<command> <balance|pay|deposit|withdraw|history|reload>
    aliases: [sa]
    permission: serveraccount.admin

permissions:
  serveraccount.admin:
    description: Access to server account commands
    default: op
