name: CORASpectator
version: '1.0.0'
main: dev.hjjang.coraspectator.CORASpectator
api-version: '1.21'
description: Controlled spectator sessions for staff investigation
author: CORA Team

commands:
  cora-spectate:
    description: Manage spectator sessions
    usage: |
      /cora-spectate start <staff> <target> <duration_seconds>
      /cora-spectate end <staff>
      /cora-spectate status
    permission: coraspectator.admin
    permission-message: You don't have permission to use this command

permissions:
  coraspectator.use:
    description: Allows being put in spectator session
    default: op
  coraspectator.admin:
    description: Allows managing spectator sessions
    default: op
